baseurl: "https://omniopencon.org"
title: "OmniOpenCon"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "G-6YLFK34GVP"

params:
  # Conference info
  Name: "OmniOpenCon"
  Description: "A gathering of people, projects and communities working with open source / data / science / hardware / education"
  Date: "September 26-28, 2024"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Aula Magna & Central Library, POLITEHNICA Bucharest"
  Address: "Splaiul Independenței 313"
  City: "Bucharest"
  #State: "Quintana"
  MapsLocation: "UNSTPB Aula Magna"
  Images: ["/img/badge.png"]
  GoogleMapsKey: "AIzaSyBKGXP4QNvkxcY5_7MxLr7ud09xrSJztJU"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - connect
    - speakers
    - schedule
    - sponsors
    - partners
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    workshops: "Workshops"
    hackathon: "Hackathon"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"
    connect: "Get Connected!"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://forms.gle/z9EcRCwfV5gZCsMd6"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/rosedu/omniopencon"

  Connect:
    - name: "Discord"
      logo: "/img/logo-discord.jpg"
      url: "https://bit.ly/OmniOpenCon"
    - name: "Facebook"
      logo: "/img/logo-facebook.png"
      url: "https://www.facebook.com/omniopencon"
    - name: "Instagram"
      logo: "/img/logo-instagram.png"
      url: "https://www.instagram.com/omniopencon"

  Contact:
    - name: "E-mail"
      logo: "/img/logo-email.png"
      url: "mailto:contact@omniopencon.org"
    - name: "Discord"
      logo: "/img/logo-discord.jpg"
      url: "https://bit.ly/OmniOpenCon"

  # List of Sponsors
  Sponsors:
    - name: "Keysight Technologies Romania"
      logo: "/img/logo-keysight.png"
      url: "https://www.linkedin.com/company/ixia-romania/"

  # List of Partners
  Partners:
    - name: "POLITEHNICA Bucharest"
      logo: "/img/logo-unstpb.png"
      url: "https://www.upb.ro"
    - name: "Faculty of Automatic Controls and Computers"
      logo: "/img/logo-acs.png"
      url: "https://acs.pub.ro"
    - name: "ROSEdu (Romanian Open Source Education)"
      logo: "/img/logo-rosedu.png"
      url: "https://www.rosedu.org"

  # The entire schedule
  Schedule:
    - name: "Check-in"
      time: "08:30"
      description: "Welcome, get to know the venue, connect with others."

    - name: "Talks (session 1)"
      time: "09:00"
      description: "First set of 3 talks, 30 minutes slot each: presentation + questions"

    - name: "Coffee / Tea Break"
      time: "10:30"
      description: "A well deserved break. Grab some coffee or tea, connect with others."

    - name: "Talks (session 2)"
      time: "11:00"
      description: "Second set of 3 talks, 30 minutes slot each: presentation + questions"

    - name: "Lunch Break"
      time: "12:30"
      description: "Lunch break on your own. Dining options around the POLITEHNICA campus will be provided."

    - name: "Talks (session 3)"
      time: "14:00"
      description: "Third set of 3 talks, 30 minutes slot each: presentation + questions"

    - name: "Coffee / Tea Break"
      time: "15:30"
      description: "A well deserved break. Grab some coffee or tea, connect with others."

    - name: "Talks (session 4)"
      time: "16:00"
      description: "Fourth set of 3 talks, 30 minutes slot each: presentation + questions"

    - name: "Networking"
      time: "17:30"
      description: "On-site networking with speakers, organizers, participants. A good time to make friends and open up collaboration options."

  Workshops:
    - name: "Check-in"
      time: "08:30"
      description: "Welcome, get to know the venue, connect with others."

    - name: "Workshops (session 1)"
      time: "09:00"
      description: "First workshop slot"

    - name: "Lunch Break"
      time: "12:30"
      description: "Lunch break on your own. Dining options around the POLITEHNICA campus will be provided."

    - name: "Workshops (session 2)"
      time: "14:00"
      description: "Second workshop slot"

    - name: "Networking"
      time: "17:30"
      description: "On-site networking with speakers, organizers, participants. A good time to make friends and open up collaboration options."
