services:
  hugo:
    container_name: omniopencon-site
    image: "peaceiris/hugo:v${HUGO_VERSION:-0.133.0}"
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
