baseurl: "https://omniopencon.org"
title: "OmniOpenCon"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "G-6YLFK34GVP"

params:
  # Conference info
  Name: "OmniOpenCon"
  Description: "A gathering of people, projects and communities working with open source / data / science / hardware / education"
  Date: "September 26-28, 2024"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Aula Magna & Central Library, POLITEHNICA Bucharest"
  Address: "Splaiul Independenței 313"
  City: "Bucharest"
  #State: "Quintana"
  MapsLocation: "UNSTPB Aula Magna"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyBKGXP4QNvkxcY5_7MxLr7ud09xrSJztJU"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    workshops: "Workshops"
    hackathon: "Hackathon"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://forms.gle/z9EcRCwfV5gZCsMd6"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Keysight Technologies Romania"
      logo: "/img/logo-keysight.png"
      url: "https://www.linkedin.com/company/ixia-romania/"

  # List of Partners
  Partners:
    - name: "POLITEHNICA Bucharest"
      logo: "/img/logo-unstpb.png"
      url: "https://www.upb.ro"
    - name: "Faculty of Automatic Controls and Computers"
      logo: "/img/logo-acs.png"
      url: "https://acs.pub.ro"
    - name: "ROSEdu (Romanian Open Source Education)"
      logo: "/img/logo-rosedu.png"
      url: "https://www.rosedu.org"

  # The entire schedule
  Schedule:
    - name: "Check-in"
      time: "8h30"

    - name: "Coffee / Tea Break"
      time: "10h30"

    - name: "Lunch"
      time: "12h30"

    - name: "Coffee / Tea Break"
      time: "15h30"
